/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Done
package edu.pucmm.eict;

import edu.pucmm.eict.controllers.AdminController;
import edu.pucmm.eict.controllers.GeneralControllers;
import io.javalin.Javalin;
import io.javalin.plugin.rendering.JavalinRenderer;
import io.javalin.plugin.rendering.template.JavalinThymeleaf;
import edu.pucmm.eict.services.DatabaseSetupServices;
import java.sql.SQLException;

public class App {

    private static String connMode = "";
    public static void main(String[] args) throws SQLException {

        if (args.length > 0) {
            connMode = args[0];
            System.out.println("Modo: "+connMode);
        }
        Javalin app = Javalin.create(config -> {
            config.addStaticFiles("/public");
        }).start(getHerokuAssignedPort());
        
        JavalinRenderer.register(JavalinThymeleaf.INSTANCE, ".html");

        DatabaseSetupServices.startDb();
        // DataBaseConnServices.getInstance().testConn();
        // DatabaseSetupServices.createTables();

        // ShoppingCartServices.getInstance().createProduct(new Product("Monitor DELL", new BigDecimal(8000)));
        // ShoppingCartServices.getInstance().createProduct(new Product("4GB RAM DDR4", new BigDecimal(4000)));

        // ProductServices productServices = new ProductServices();
        // System.out.println(productServices.getLastId());

        new AdminController(app).applyRoutes();
        new GeneralControllers(app).applyRoutes();
    }

    static int getHerokuAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 3000; //Retorna el puerto por defecto en caso de no estar en Heroku.
    }

    public static String getConnMode(){
        return connMode;
    }
}
