/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.pucmm.eict;

import edu.pucmm.eict.controllers.AdminController;
import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {
        Javalin app = Javalin.create(config -> {
            config.addStaticFiles("/public");
        }).start(3000);
        
        new AdminController(app).applyRoutes();
    }
}
